chore(hooks): enhance post-commit script with improved configuration and structure; perform test

diff --git a/.husky/post-commit b/.husky/post-commit
--- a/.husky/post-commit
+++ b/.husky/post-commit
@@ -1,1 +1,17 @@
-git push https://github.com/Jose-leandro/Estrelar.git develop
+# Retrieve the remote URL of the current repository
+REMOTE_URL=$(git config --get remote.origin.url)
+
+# Define the expected remote URL
+EXPECTED_REMOTE_URL="https://github.com/Jose-leandro/Stellar.git"
+
+# Check if the current remote URL matches the expected URL
+if [[ "$REMOTE_URL" == "$EXPECTED_REMOTE_URL" ]]; then
+  echo "Remote URL matches. Proceeding with safe actions. Make the push for 'https://github.com/Jose-leandro/Stellar.git' for 'develop'"
+  
+  # Example safe action: Push changes to the 'develop' branch
+  git push "$EXPECTED_REMOTE_URL" develop
+else
+  echo "Warning: Remote URL does not match the expected repository."
+  echo "Aborting post-commit actions."
+  exit 1
+fi
